// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfziyuzuenjjjdztycw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZnppeXV6dWVuampqZHp0eWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDMyNjMsImV4cCI6MjA2NTQ3OTI2M30.6ZE73TCMbWGVzm1z7WC22GuxVozrLRdGoOdMJXrrAdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);